name: RepoCheckin

on:
  push:
    branches:
      '**'

  pull_request:
    branches:
      '**'
      
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Test using Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12'

      - run: npm install jest --global

      - run: npm test ./Tests

      - name: GetRepoVersion
        if: success()
        id: GetRepoVer
        uses: ./

      - name: IncreaseVersion
        id: IncreaseVer
        shell: pwsh
        run: |
          $SplitVer = ${{ steps.GetRepoVer.outputs.version }} -split '\.'
          $NewVer = "$($SplitVer[0]).$($SplitVer[1]).$([int]$SplitVer[2] + 1)"
          Write-Output "::set-output name=version::$NewVer"

      - name: Update version badge
        uses: jeffbuenting/UpdateCustomBadge@jeffbuenting-patch-1
        with: 
          vertype: steps.GetRepoVer.outputs.vertype
          version: steps.IncreaseVer.outputs.version